# Generated by Django 3.2.4 on 2021-06-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0002_moviedb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieDB',
        ),
    ]
